### ISSUE TITLE
about revolver and deagle

### ISSUE THREAD

**Issue by 3DarkDays** [imi-tat0r/unmatched_snippets#2]
Is there any plan to release the plugin code for real-time replacement of Deagle and Revolver? When I was magical about the unmatch plugin, I also lamented the trouble of csgo being unable to open the inventory.

**Comment by imi-tat0r** [comment]
soon

**Comment by 3DarkDays** [comment]
> soon

thank you so much

**Comment by imi-tat0r** [comment]
source and binary are available now
